version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5014:5014"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
